import { dirname, join } from 'path';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import type { WorkspaceConfigSnapshot, WorkspaceComponentSummary } from './config';
import {
  buildBootstrapRefinementsForProject,
  buildBootstrapUnresolvedForProject
} from './bootstrap-analysis';

export interface GeneratedCiFile {
  path: string;
  content: string;
}

export const REQUIRED_CI_SECRETS = ['LICELL_ACCOUNT_ID', 'LICELL_AK', 'LICELL_SK', 'LICELL_REGION'] as const;
export const GITHUB_WORKFLOW_DEFAULT_PATH = '.github/workflows/licell-deploy.yml';
export const GITLAB_PIPELINE_DEFAULT_PATH = '.gitlab-ci.licell.yml';

function indent(lines: string[], spaces = 2) {
  const prefix = ' '.repeat(spaces);
  return lines.map((line) => (line ? `${prefix}${line}` : line));
}

export function getDeployableComponents(snapshot: WorkspaceConfigSnapshot): WorkspaceComponentSummary[] {
  const components = snapshot.mode === 'workspace'
    ? snapshot.components
    : [{
      name: snapshot.componentName || 'default',
      path: snapshot.componentPath,
      project: snapshot.project,
      matched: true,
      defaultComponent: true
    } satisfies WorkspaceComponentSummary];

  return components.filter((component) => {
    const deployType = component.project.deployType;
    return deployType === 'static' || deployType === 'api' || deployType === 'task';
  });
}

function getComponentBootstrapGuidance(component: WorkspaceComponentSummary) {
  const deployType = component.project.deployType === 'static' || component.project.deployType === 'api' || component.project.deployType === 'task'
    ? component.project.deployType
    : null;
  const unresolved = buildBootstrapUnresolvedForProject(component.name, deployType, component.project);
  const refinements = buildBootstrapRefinementsForProject({
    component: component.name,
    deployType,
    project: component.project
  });
  return { unresolved, refinements };
}

function renderBootstrapGuidanceComments(
  snapshot: WorkspaceConfigSnapshot,
  commentPrefix: string,
  components = getDeployableComponents(snapshot)
) {
  const lines = [
    `${commentPrefix} Generated by licell deploy-only CI scaffolding.`,
    `${commentPrefix} This file only wires CI to licell deploy commands; build/test stages stay outside licell.`
  ];
  let hasGuidance = false;
  for (const component of components) {
    const guidance = getComponentBootstrapGuidance(component);
    if (guidance.unresolved.length === 0 && guidance.refinements.length === 0) continue;
    if (!hasGuidance) {
      lines.push(`${commentPrefix} Deployment refinement hints:`);
      hasGuidance = true;
    }
    for (const unresolved of guidance.unresolved) {
      lines.push(`${commentPrefix} - ${component.name}: unresolved ${unresolved.field} -> ${unresolved.commandTemplate}`);
    }
    for (const refinement of guidance.refinements) {
      lines.push(`${commentPrefix} - ${component.name}: ${refinement.reason} -> ${refinement.commandTemplate}`);
    }
  }
  if (!hasGuidance) {
    lines.push(`${commentPrefix} No additional licell bootstrap refinements detected from the current project config.`);
  }
  return lines;
}

function resolveArtifactPath(component: WorkspaceComponentSummary) {
  return component.project.artifact?.kind === 'directory'
    ? component.project.artifact.path || component.project.dist || component.path || '.'
    : component.project.artifact?.entry || component.project.entry || component.path || '.';
}

function renderGithubArtifactCheck(componentName: string, artifactPath: string | undefined) {
  const targetPath = artifactPath || '.';
  return indent([
    '- name: Validate deploy input',
    '  shell: bash',
    '  run: |',
    `    # TODO: Ensure the deploy artifact for component ${componentName} exists before calling licell.`,
    `    test -e ${JSON.stringify(targetPath)}`
  ], 6).join('\n');
}

function renderGitlabArtifactCheck(componentName: string, artifactPath: string | undefined) {
  const targetPath = artifactPath || '.';
  return [
    `# TODO: Ensure the deploy artifact for component ${componentName} exists before calling licell.`,
    `test -e ${JSON.stringify(targetPath)}`
  ];
}

function renderGithubComponentJob(component: WorkspaceComponentSummary) {
  const artifactPath = resolveArtifactPath(component);
  const deployArgs = [`--component ${component.name}`, '--output json'];
  return [
    `  deploy-${component.name}:`,
    `    name: Deploy ${component.name}`,
    '    runs-on: ubuntu-latest',
    `    if: \${{ github.event.inputs.component == '' || github.event.inputs.component == '${component.name}' }}`,
    '    env:',
    '      LICELL_ACCOUNT_ID: ${{ secrets.LICELL_ACCOUNT_ID }}',
    '      LICELL_AK: ${{ secrets.LICELL_AK }}',
    '      LICELL_SK: ${{ secrets.LICELL_SK }}',
    '      LICELL_REGION: ${{ secrets.LICELL_REGION }}',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '      - name: Setup Node',
    '        uses: actions/setup-node@v4',
    '        with:',
    '          node-version: "20"',
    '      - name: Authenticate licell',
    '        shell: bash',
    '        run: |',
    '          npx licell@latest login --account-id "$LICELL_ACCOUNT_ID" --ak "$LICELL_AK" --sk "$LICELL_SK" --region "${LICELL_REGION:-cn-hangzhou}" --output json',
    renderGithubArtifactCheck(component.name, artifactPath),
    '      - name: Doctor',
    `        run: npx licell@latest doctor --component ${component.name} --offline --output json`,
    '      - name: Deploy',
    `        run: npx licell@latest deploy ${deployArgs.join(' ')}`
  ].join('\n');
}

export function renderGithubDeployWorkflow(snapshot: WorkspaceConfigSnapshot, components = getDeployableComponents(snapshot)): string {
  return [
    ...renderBootstrapGuidanceComments(snapshot, '#', components),
    '',
    'name: licell deploy',
    '',
    'on:',
    '  workflow_dispatch:',
    '    inputs:',
    '      component:',
    '        description: Optional component name to deploy',
    '        required: false',
    '        default: ""',
    '        type: string',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    ...components.map((component) => renderGithubComponentJob(component))
  ].join('\n');
}

function renderGitlabRules(componentName: string) {
  return [
    `    - if: '$COMPONENT == null || $COMPONENT == "" || $COMPONENT == "${componentName}"'`,
    '      when: manual',
    '    - when: never'
  ];
}

function renderGitlabComponentJob(component: WorkspaceComponentSummary) {
  const artifactPath = resolveArtifactPath(component);
  const deployArgs = [`--component ${component.name}`, '--output json'];
  return [
    `deploy:${component.name}:`,
    '  stage: deploy',
    '  image: node:20-bullseye',
    '  variables:',
    '    GIT_STRATEGY: fetch',
    '  rules:',
    ...renderGitlabRules(component.name),
    '  before_script:',
    '    - npx licell@latest login --account-id "$LICELL_ACCOUNT_ID" --ak "$LICELL_AK" --sk "$LICELL_SK" --region "${LICELL_REGION:-cn-hangzhou}" --output json',
    '  script:',
    ...renderGitlabArtifactCheck(component.name, artifactPath).map((line) => `    - ${line}`),
    `    - npx licell@latest doctor --component ${component.name} --offline --output json`,
    `    - npx licell@latest deploy ${deployArgs.join(' ')}`,
    '  allow_failure: false'
  ].join('\n');
}

export function renderGitlabDeployPipeline(snapshot: WorkspaceConfigSnapshot, components = getDeployableComponents(snapshot)): string {
  return [
    ...renderBootstrapGuidanceComments(snapshot, '#', components),
    '',
    '# Generated by `licell ci init gitlab`.',
    '# Include this file from your main `.gitlab-ci.yml` when the repo already has existing build/test pipelines.',
    '# If any component uses `licell deploy --runtime docker`, the deploy job needs a real Docker daemon.',
    '# In GitLab CI, prefer mounting the host Docker socket over Docker-in-Docker.',
    '# If nested Docker / Docker-in-Docker is unavoidable, the runner must enable `privileged = true`.',
    '# Example:',
    '# include:',
    `#   - local: '${GITLAB_PIPELINE_DEFAULT_PATH}'`,
    '',
    'stages:',
    '  - deploy',
    '',
    '# Optional CI/CD variables expected by this pipeline:',
    '# - LICELL_ACCOUNT_ID',
    '# - LICELL_AK',
    '# - LICELL_SK',
    '# - LICELL_REGION',
    '# Optional runtime variable:',
    '# - COMPONENT (set to one component name to trigger only that deploy job)',
    '',
    ...components.map((component) => renderGitlabComponentJob(component))
  ].join('\n\n');
}

export function writeGeneratedCiFile(file: GeneratedCiFile, force = false) {
  const fullPath = join(process.cwd(), file.path);
  const dir = dirname(fullPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (existsSync(fullPath) && !force) {
    const current = readFileSync(fullPath, 'utf8');
    if (current === file.content) {
      return { written: false, skipped: true };
    }
    throw new Error(`文件已存在且内容不同: ${file.path}（使用 --force 覆盖）`);
  }
  writeFileSync(fullPath, `${file.content.trimEnd()}\n`, 'utf8');
  return { written: true, skipped: false };
}
